//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Receta
    {
        public int Id { get; set; }
        public short Receta { get; set; }
        public short Insumo { get; set; }
        public int Cantidad_Usada { get; set; }
    
        public virtual Insumo Insumo1 { get; set; }
        public virtual Receta Receta1 { get; set; }
    }
}
