//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Orden
    {
        public int Id { get; set; }
        public int Orden { get; set; }
        public short Receta { get; set; }
        public int Precio { get; set; }
        public byte Estado_Orden { get; set; }
    
        public virtual Estado_Orden Estado_Orden1 { get; set; }
        public virtual Orden Orden1 { get; set; }
        public virtual Receta Receta1 { get; set; }
    }
}
