//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumo()
        {
            this.Detalle_Proveedor = new HashSet<Detalle_Proveedor>();
            this.Detalle_Receta = new HashSet<Detalle_Receta>();
            this.Detalle_Solicitud = new HashSet<Detalle_Solicitud>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public byte Unidad_Medida { get; set; }
        public int Cantidad_Actual { get; set; }
        public int Stock_Min { get; set; }
        public int Stock_Max { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Proveedor> Detalle_Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Receta> Detalle_Receta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Solicitud> Detalle_Solicitud { get; set; }
        public virtual Unidad_Medida Unidad_Medida1 { get; set; }
    }
}
