//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Financiero
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Costo { get; set; }
        public byte Tipo_Movimiento { get; set; }
    
        public virtual Tipo_Movimiento Tipo_Movimiento1 { get; set; }
    }
}
