//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receta()
        {
            this.Detalle_Orden = new HashSet<Detalle_Orden>();
            this.Detalle_Receta = new HashSet<Detalle_Receta>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
        public int Precio { get; set; }
        public byte Dificultad { get; set; }
        public byte Tipo { get; set; }
        public bool Estado { get; set; }
        public string Instruccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Orden> Detalle_Orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Receta> Detalle_Receta { get; set; }
        public virtual Dificultad Dificultad1 { get; set; }
        public virtual Tipo_Receta Tipo_Receta { get; set; }
    }
}
