//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public short Mesa { get; set; }
        public System.DateTime Fecha_Reserva { get; set; }
        public byte Tipo_Reserva { get; set; }
        public Nullable<int> Cliente { get; set; }
        public byte Capacidad_Ocupada { get; set; }
        public Nullable<byte> Estado { get; set; }
    
        public virtual Estado_Reserva_Online Estado_Reserva_Online { get; set; }
        public virtual Mesa Mesa1 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Tipo_Reserva Tipo_Reserva1 { get; set; }
    }
}
