//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LISTAR_ORDENES_A_COCINA
    {
        public int Orden { get; set; }
        public string Hora_Encargo { get; set; }
        public short Numero_Mesa { get; set; }
        public string Receta { get; set; }
        public string Dificultad { get; set; }
        public string Descripcion { get; set; }
    }
}
