//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_LISTAR_MESAS
    {
        public short Id { get; set; }
        public short Numero { get; set; }
        public byte Capacidad { get; set; }
        public bool Estado { get; set; }
    }
}
